version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./prisma:/app/prisma         # monta la cartella con il file SQLite
    environment:
      NODE_ENV: production
    restart: unless-stopped
