version: 2.1

jobs:
  build-and-test:
    docker:
      - image: "cimg/node:18.17"  # Immagine con Node.js preinstallato
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      
      - run:
          name: Install dependencies
          command: npm ci
      
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      
      - run:
          name: Run tests
          command: npm run test

workflows:
  build-and-test:
    jobs:
      - build-and-test